# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/rxtsslfc/tundra_kernel
          kernel-dir: msm-5.4.233
          kernel-branch: android-13-rebase
          config: stock_tundra_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: android-13
          aosp-clang-version: r450784d
          disable-lto: true
          anykernel3: true
