# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/rxtsslfc/tundra_kernel
          kernel-dir: msm-5.4.180
          kernel-branch: thirteen-plus
          config: config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11.0.2
          aosp-clang-version: r383902b1
          disable-lto: true
          anykernel3: true
